[tool.poetry]
name = "django-admin-popup"
version = "0.1.0"
description = ""
authors = ["Hosoi Eda <hrabr88ov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
